# Generated by Django 4.2.29 on 2026-04-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useractivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activities'},
        ),
    ]
