# Generated by Django 4.2.29 on 2026-04-25 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'is_instructor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
