# Generated by Django 4.2.29 on 2026-04-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_batch_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetinventory',
            options={'verbose_name': 'Asset Inventory', 'verbose_name_plural': 'Asset Inventories'},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
    ]
