# Generated by Django 6.0.5 on 2026-06-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_batch_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='location',
            field=models.CharField(blank=True, help_text='Room, campus, lab name, or physical address.', max_length=200),
        ),
        migrations.AlterField(
            model_name='batch',
            name='schedule',
            field=models.CharField(help_text='e.g. Mon–Fri 10:00 AM – 12:00 PM', max_length=200),
        ),
    ]
