# Generated by Django 4.2.29 on 2026-04-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_certificate_course_alter_certificate_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name_plural': 'Lesson Progresses'},
        ),
    ]
