# Generated by Django 4.2.29 on 2026-05-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lessonprogress_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload custom certificate image or PDF', null=True, upload_to='certificates/'),
        ),
    ]
