# Generated by Django 6.0.4 on 2026-05-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_certificate_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='cf_stream_status',
            field=models.CharField(choices=[('none', 'None'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cf_stream_video_id',
            field=models.CharField(blank=True, help_text='Cloudflare Stream video UID', max_length=200),
        ),
    ]
