# Generated by Django 6.0.5 on 2026-06-22 04:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_lesson_video_url_lesson_cf_stream_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
