# Generated by Django 6.0.5 on 2026-06-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_certificate_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.ImageField(blank=True, help_text='Upload certificate template image (JPG/PNG) for this course', null=True, upload_to='certificate_templates/'),
        ),
    ]
